#!/bin/sh

set -e

if [ $# -lt 1 ]; then
  echo "Need to specify program to build" >&2
  exit 4
fi
pgm=$1

DBG_DS="$(hlq).DEBUG.SLD"
ADA_DS="$(hlq).DEBUG.ADA"
MEM_DBG="${DBG_DS}(${pgm})"
MEM_ADA="${ADA_DS}(${pgm})"

xmplib="$(hlq).ASMXMP.LOAD"

dls "${xmplib}" >/dev/null 2>/dev/null
if [ $? -gt 0 ]; then
  dtouch -tPDS -ru ${xmplib}
else
  set +e
  mrm "${xmplib}(${pgm})" >/dev/null 2>/dev/null
  set -e
fi

as --LIST,SUPRWARN\(425,434\) "--gadata=//'${MEM_ADA}'" ${pgm}.s >${pgm}.lst
mvscmd --pgm=XSLDMOD --steplib=$SLDLOAD --args='DDNAME (ASM' --sysadata="${MEM_ADA}" --sldlogic="$MEM_DBG" --sysprint=* --systerm=*

ld -o"//'${xmplib}(${pgm})'" ${pgm}.o

echo "${xmplib}(${pgm}) created"
