#!/bin/sh

out="$(hlq).ASMXMP.OUT"
drm "${out}"
dtouch -tseq -l2048 -rvb "${out}"

set -e

rdlib=$(echo "$(hlq).ASMXMP.DATA")

mem=$(mls "${rdlib}")
if [ "${mem}" != "NEWMEM" ]; then
  echo "Run CRTMEM to create the member before trying to read"
  exit 4
fi

xmplib="$(hlq).ASMXMP.LOAD"
mvscmd --steplib=$xmplib --indd="SYS1.MACLIB:$HOME:${rdlib}" --pgm=RDJFCB --outdd="${out}"

echo "List of entries in INDD concatenation (see ${out})"
cat "//'${out}'"